[book]
authors = ["Philipp Schroer"]
language = "en"
multilingual = false
src = "src"
title = "Caesar Documentation"

[output.html]
git-repository-url = "https://github.com/Philipp15b/caesar"
edit-url-template = "https://github.com/Philipp15b/caesar/edit/master/docs/{path}"

[preprocessor.graphviz]
command = "mdbook-graphviz"
