[book]
authors = ["Philipp Schroer"]
language = "en"
multilingual = false
src = "src"
title = "Caesar Documentation"

[output.html]
git-repository-url = "https://github.com/moves-rwth/caesar"
edit-url-template = "https://github.com/moves-rwth/caesar/edit/master/docs/{path}"
cname = "www.caesarverifier.org"

[preprocessor.graphviz]
command = "mdbook-graphviz"
